version: '3.3' # 指定docker-compose 版本
services: # 要拉起的服务们
  certd:
#    build:
#        context: ./
#        dockerfile: Dockerfile
#                                                              ↓↓↓↓↓  修改镜像版本号
    image: registry.cn-shenzhen.aliyuncs.com/handsfree/certd:${TAG}
    container_name: certd # 容器名
    restart: unless-stopped # 重启
    volumes:
      #   ↓↓↓↓↓  修改数据库以及证书存储路径
      - /data/certd:/app/data
    ports: # 端口映射
      - "7001:7001"
    environment:
      - TZ=Asia/Shanghai
      - certd_auth_jwt_secret=changeme
#                               ↑↑↑↑↑   注意修改成你的自定义密钥

