version: '3.3' # 指定docker-compose 版本
services: # 要拉起的服务们
  certd:
#    build:
#        context: ./
#        dockerfile: Dockerfile
    image: registry.cn-shenzhen.aliyuncs.com/handsfree/certd:v${TAG}
    container_name: certd # 容器名
    restart: unless-stopped # 重启
    volumes: # 挂载目录
      - /data/certd:/app/data
    ports: # 端口映射
      - "7001:7001"
    environment:
      - TZ=Asia/Shanghai
      - CERTD_AUTH_JWT_KEY=changeme
      #注意修改成你的自定义密钥 ↑↑↑↑↑

